/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;

	public class ConditionButtonUI extends View {
		public var btn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":60,"height":22},"compId":2,"child":[{"type":"Button","props":{"var":"btn","top":0,"skin":"commers/btn3.png","sizeGrid":"5,5,5,5","right":0,"left":0,"labelSize":18,"labelColors":"#223344,#FFFFFF,#FFFFFF","label":"蓝色","bottom":0},"compId":3}],"loadList":["commers/btn3.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}