/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;
	import script.prodCustomer.CustomerEditController;

	public class CustomEditPanelUI extends View {
		public var mainpanel:Panel;
		public var editPanel:Panel;
		public var prodVBox:VBox;
		public var prodPreImg:Image;
		public var totalPrice:Label;
		public var bottomBox:Box;
		public var okbtn:Button;
		public var cancelbtn:Button;
		public var addToCart:Button;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("prodCustom/CustomEditPanel");

		}

	}
}