/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;
	import script.prodCustomer.CustomerProdCategoryController;

	public class CustomerProdCategoryPanelUI extends View {
		public var mainpanel:Panel;
		public var categoryList:List;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("prodCustom/CustomerProdCategoryPanel");

		}

	}
}