/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;

	public class paramRadioUI extends View {

		override protected function createChildren():void {
			super.createChildren();
			loadScene("prodCustom/paramRadio");

		}

	}
}