/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.prodCustomer.ProdChooseController;

	public class ProdChoosePanelUI extends View {
		public var mainpanel:Panel;
		public var myaddresstxt:Text;
		public var conditionList:List;
		public var prodList:List;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("prodCustom/ProdChoosePanel");

		}

	}
}