/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;

	public class ProdCategoryItemUI extends View {
		public var frame:Image;
		public var img:Image;
		public var categoryName:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":200,"height":200},"compId":2,"child":[{"type":"Image","props":{"var":"frame","top":0,"skin":"commers/inputerror.png","sizeGrid":"5,5,5,5","right":0,"left":0,"bottom":0},"compId":5},{"type":"Image","props":{"width":200,"var":"img","skin":"comp/image.png","height":200},"compId":3},{"type":"Label","props":{"var":"categoryName","text":"T桖","strokeColor":"#2dc011","stroke":1,"right":5,"fontSize":16,"font":"SimHei","bottom":2,"bold":false,"align":"right"},"compId":4}],"loadList":["commers/inputerror.png","comp/image.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}