/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;
	import script.prodCustomer.ProdEditController;

	public class ProdEditItemUI extends View {
		public var editBox:Box;
		public var prodImg:Image;
		public var customImg:Image;
		public var maskimg:Image;
		public var imgframe:Image;
		public var rotateBox:Box;
		public var dragBox:Box;
		public var chooseImg:Button;
		public var resetBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("prodCustom/ProdEditItem");

		}

	}
}