/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.prodCustom {
	import laya.ui.*;
	import laya.display.*;

	public class ProdParamItemUI extends View {
		public var conLbl:Label;
		public var btnList:List;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1200,"height":0},"compId":2,"child":[{"type":"Label","props":{"y":2,"x":0,"var":"conLbl","text":"颜色：","fontSize":20,"font":"SimHei"},"compId":3},{"type":"List","props":{"width":1100,"var":"btnList","left":60,"height":22},"compId":7}],"loadList":[],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}