/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView.items {
	import laya.ui.*;
	import laya.display.*;

	public class MatCategoryItemUI extends View {
		public var selbtn:Button;
		public var selfIcon:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Button","props":{"y":1,"x":1,"width":200,"var":"selbtn","stateNum":3,"skin":"uiCommonUpdate/metCatBtn.png","labelSize":18,"labelColors":"#000000,#003dc6,#003dc6","labelBold":true,"label":"户外写真","height":64,"sizeGrid":"0,24,0,16"},"compId":3},{"type":"Image","props":{"y":0,"x":132,"width":20,"var":"selfIcon","skin":"commers/client.png","mouseEnabled":false,"height":20},"compId":4}],"loadList":["uiCommonUpdate/metCatBtn.png","commers/client.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}