/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView.items {
	import laya.ui.*;
	import laya.display.*;

	public class MatProcessItemUI extends View {
		public var btn:Button;
		public var arrow:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Button","props":{"width":343,"var":"btn","stateNum":2,"skin":"uiCommonUpdate/matprocess.png","selected":false,"labelSize":27,"labelColors":"#FFFFFF,#003dc6,#003dc6","label":"户外PP背胶(户外写真)     ","height":96,"sizeGrid":"6,5,7,5"},"compId":3,"child":[{"type":"Image","props":{"y":32,"x":158,"var":"arrow","skin":"iconsNew/bigArrow.png","right":10},"compId":4}]}],"loadList":["uiCommonUpdate/matprocess.png","iconsNew/bigArrow.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}