/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView.items {
	import laya.ui.*;
	import laya.display.*;

	public class PicSimpleItemUI extends View {
		public var selframe:Image;
		public var pic:Image;
		public var fileName:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":250,"height":275},"compId":2,"child":[{"type":"Image","props":{"top":0,"skin":"uiCommonUpdate/grayFrame.png","sizeGrid":"3,3,3,3","right":0,"left":0,"bottom":0},"compId":7},{"type":"Image","props":{"y":0,"x":0,"var":"selframe","top":0,"skin":"commers/inputfocus.png","sizeGrid":"5,5,5,5","right":0,"left":0,"bottom":0},"compId":6},{"type":"Image","props":{"y":125,"x":125,"width":240,"var":"pic","skin":"iconsNew/defaultImg.png","height":240,"anchorY":0.5,"anchorX":0.5},"compId":3},{"type":"Label","props":{"x":35,"wordWrap":false,"width":180,"var":"fileName","valign":"middle","text":"名称.jpg 宽 3256 名称","overflow":"scroll","height":20,"fontSize":14,"font":"SimHei","color":"#485157","bottom":5,"bold":true,"align":"center"},"compId":4}],"loadList":["uiCommonUpdate/grayFrame.png","commers/inputfocus.png","iconsNew/defaultImg.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}