/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView.items {
	import laya.ui.*;
	import laya.display.*;

	public class SmallPictureItemUI extends View {
		public var pic:Image;
		public var selFrame:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":120,"height":120},"compId":2,"child":[{"type":"Image","props":{"y":60,"x":60,"width":120,"var":"pic","skin":"comp/image.png","height":120,"anchorY":0.5,"anchorX":0.5},"compId":3},{"type":"Image","props":{"y":0,"x":0,"var":"selFrame","top":0,"skin":"commers/inputfocus.png","sizeGrid":"5,5,5,5","right":0,"left":0,"bottom":0},"compId":5}],"loadList":["comp/image.png","commers/inputfocus.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}