/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.picManager {
	import laya.ui.*;
	import laya.display.*;
	import script.picUpload.PictureCheckControl;

	public class PicCheckPanelUI extends View {
		public var imgbg:Image;
		public var mainpanel:Panel;
		public var img:Image;
		public var yixingimg:Image;
		public var closeBtn:Button;
		public var fileName:Label;
		public var fileType:Label;
		public var colorSpace:Label;
		public var dpi:Label;
		public var sizetxt:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("picManager/PicCheckPanel");

		}

	}
}