/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.CmykInputControl;
	import script.picUpload.CreateFolderController;

	public class CreateFolderPanelUI extends View {
		public var closeBtn:Button;
		public var btnSureCreate:Button;
		public var input_folename:TextInput;
		public var delBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/CreateFolderPanel");

		}

	}
}