/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.workpanel.EffectPreviewController;

	public class EffectPreviewPanelUI extends View {
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/EffectPreviewPanel");

		}

	}
}