/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.workpanel.ImageEffectControlller;

	public class MatAndProcEffectPanelUI extends View {
		public var imgbg:Image;
		public var mainpanel:Panel;
		public var titlelbl:Label;
		public var contentPanel:Panel;
		public var img:Image;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/MatAndProcEffectPanel");

		}

	}
}