/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.workpanel.MatAndProcFlowController;

	public class MaterialAdProcFlowPanelUI extends View {
		public var mainpanel:Panel;
		public var leftpanel:Panel;
		public var originimg:Image;
		public var backimg:Image;
		public var yixingimg:Image;
		public var partImg:Image;
		public var rightpanel:Panel;
		public var rightbox:VBox;
		public var matProcContainer:Image;
		public var operateArea:Panel;
		public var confirmBtn:Button;
		public var saveBtn:Text;
		public var closeBtn:Button;
		public var effectBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/MaterialAdProcFlowPanel");

		}

	}
}