/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.workpanel.MaterialChooseController;

	public class MaterialListPanelUI extends View {
		public var tabpanel:Panel;
		public var matpanel:Panel;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/MaterialListPanel");

		}

	}
}