/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.uiTool.AvgLayHBox;
	import script.uiTool.GlowButton;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.workpanel.MyWorkController;

	public class MyWorkPanelUI extends View {
		public var mainpanel:Panel;
		public var searchBtn:Button;
		public var addWechat:Button;
		public var orderBtn:Button;
		public var capacityProgress:ProgressBar;
		public var leftCapacityLbl:Label;
		public var picList:List;
		public var uploadBtn:Button;
		public var upgradeStorage:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/MyWorkPanel");

		}

	}
}