/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.uiTool.BtnMouseCusor;
	import script.uiTool.ButtonEffect;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.prefabScript.OderTopFlowController;
	import script.workpanel.OrderSelectPicController;

	public class OrderPicManagerPanelUI extends View {
		public var folderbox:Box;
		public var btnroot:Label;
		public var flder0:Label;
		public var flder1:Label;
		public var flder2:Label;
		public var searchInput:TextInput;
		public var btnUploadPic:Button;
		public var btnNewFolder:Button;
		public var batchDelete:Button;
		public var freshbtn:Button;
		public var refreshTxt:Text;
		public var radiosel:CheckBox;
		public var picList:List;
		public var upgradestore:Box;
		public var prgcap:ProgressBar;
		public var leftcapacity:Label;
		public var saveTempBtn:Text;
		public var nextBtn:Button;
		public var step1:Box;
		public var step2:Box;
		public var step3:Box;
		public var step4:Box;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/OrderPicManagerPanel");

		}

	}
}