/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.uiTool.GlowButton;
	import script.order.OrderTypeChooseController;

	public class OrderTypePanelUI extends View {
		public var mainPanel:Panel;
		public var addbox:HBox;
		public var myaddresstxt:Text;
		public var changeAddr:Button;
		public var outputbox:HBox;
		public var paintOrderBtn:Button;
		public var dingzhiBtn:Button;
		public var productBtn:Button;
		public var zipaiBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/OrderTypePanel");

		}

	}
}