/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.uiTool.BtnMouseCusor;
	import script.uiTool.ButtonEffect;
	import laya.display.Text;
	import script.picUpload.PicManagerController;

	public class PicManagerPanelUI extends View {
		public var prgcap:ProgressBar;
		public var leftcapacity:Label;
		public var folderbox:Box;
		public var btnroot:Label;
		public var flder0:Label;
		public var flder1:Label;
		public var flder2:Label;
		public var btnorder:Button;
		public var upgradestore:Box;
		public var picList:List;
		public var btnUploadPic:Button;
		public var btnNewFolder:Button;
		public var batchDelete:Button;
		public var freshbtn:Button;
		public var refreshTxt:Text;
		public var radiosel:CheckBox;
		public var searchInput:TextInput;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/PicManagerPanel");

		}

	}
}