/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.workpanel.ProcListController;

	public class ProcListPanelUI extends View {
		public var proclist:Panel;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/ProcListPanel");

		}

	}
}