/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.workpanel.RelatedChooseController;

	public class RelatedPicChoosePanelUI extends View {
		public var mainpanel:Panel;
		public var title:Label;
		public var originList:List;
		public var originPic:Image;
		public var originFileName:Label;
		public var backPartPic:Image;
		public var effectPic:Image;
		public var yixingPic:Image;
		public var piclist:List;
		public var btnok:Button;
		public var batchOk:Button;
		public var closeBtn:Button;
		public var cancelBtn:Text;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/RelatedPicChoosePanel");

		}

	}
}