/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.picUpload.SetRelatedConfirmContoller;

	public class SetRelatedConfirmPanelUI extends View {
		public var mainpanel:Panel;
		public var mainview:Image;
		public var msgtxt:Label;
		public var btnSp:Sprite;
		public var okbtn:Button;
		public var cancelbtn:Button;
		public var closebtn:Button;
		public var originPic:Image;
		public var relatedPic:Image;
		public var relatename:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/SetRelatedConfirmPanel");

		}

	}
}