/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;
	import script.workpanel.VideoPlayPanel;

	public class VideoPlayPanelUI extends Scene {
		public var closebtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/VideoPlayPanel");

		}

	}
}