/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.CbcPreviewController;

	public class CbcPreViewPanelUI extends View {
		public var waittingPanel:Panel;
		public var leftTime:Label;
		public var loadingTips:Label;
		public var rollTip:Label;
		public var demonImg:Image;
		public var mainpanel:Panel;
		public var imgList:List;
		public var okbtn:Button;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/CbcPreViewPanel");

		}

	}
}