/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.OderTopFlowController;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.order.ChooseDeliveryTimeControl;

	public class ChooseDeliveryTimePanelUI extends View {
		public var step1:Box;
		public var step2:Box;
		public var step3:Box;
		public var step4:Box;
		public var deliverdateBoc:HBox;
		public var deliveryDate0:Label;
		public var deliveryDate1:Label;
		public var deliveryDate2:Label;
		public var deliveryDate3:Label;
		public var deliveryDate4:Label;
		public var orderlist:List;
		public var timepreferRdo:RadioGroup;
		public var setdefaultbtn:Button;
		public var countdown:Label;
		public var manufatureList:HBox;
		public var deliveryTypelist:List;
		public var productNum:Label;
		public var totalprice:Label;
		public var disocuntprice:Label;
		public var rawprice:Label;
		public var savebtn:Text;
		public var paybtn:Button;
		public var delmoney:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/ChooseDeliveryTimePanel");

		}

	}
}