/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.order.DakouSettingController;

	public class DakouPanelUI extends View {
		public var mainpanel:Panel;
		public var productlist:List;
		public var btnok:Button;
		public var batchEdit:CheckBox;
		public var cancelBtn:Text;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/DakouPanel");

		}

	}
}