/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;

	public class MaterialNameItemUI extends View {
		public var matbtn:Button;
		public var grayimg:Image;
		public var selfIcon:Image;
		public var manuFacIcon:Image;
		public var moreBtn:Button;
		public var manufactureName:Label;
		public var tipImg:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":400},"compId":2,"child":[{"type":"Button","props":{"y":7,"x":0,"width":400,"var":"matbtn","stateNum":3,"skin":"uiCommonUpdate/matBtn.png","labelSize":24,"labelFont":"SimHei","labelColors":"#262B2E,#003dc6,#003dc6","labelAlign":"center","label":"户内PP背胶（户内写真）","height":44,"disabled":false,"sizeGrid":"7,23,12,28"},"compId":8,"child":[{"type":"Image","props":{"var":"grayimg","top":0,"skin":"uiCommonUpdate/grayDisbale.png","sizeGrid":"2,2,2,2","right":0,"left":0,"bottom":0},"compId":9}]},{"type":"Image","props":{"y":5,"width":20,"var":"selfIcon","skin":"commers/client.png","right":10,"mouseEnabled":false,"height":20},"compId":11},{"type":"Image","props":{"y":7,"width":20,"var":"manuFacIcon","skin":"commers/star.png","mouseEnabled":false,"height":20},"compId":10},{"type":"Button","props":{"y":7,"width":48,"var":"moreBtn","skin":"commers/btn2.png","sizeGrid":"3,3,3,3","right":10,"labelFont":"SimHei","label":"更多","height":18},"compId":12},{"type":"Label","props":{"y":0,"x":22,"var":"manufactureName","text":"义乌物与","fontSize":16,"font":"SimHei","color":"#003dc6","bgColor":"#e4e4e4"},"compId":13},{"type":"Image","props":{"y":9,"width":20,"visible":false,"var":"tipImg","skin":"iconsNew/techTip.png","right":0,"height":20},"compId":15}],"loadList":["uiCommonUpdate/matBtn.png","uiCommonUpdate/grayDisbale.png","commers/client.png","commers/star.png","commers/btn2.png","iconsNew/techTip.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}