/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.MoreProductController;

	public class MoreProductPanelUI extends View {
		public var mainpanel:Panel;
		public var categoryName:Label;
		public var productList:List;
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/MoreProductPanel");

		}

	}
}