/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;

	public class OrderAddressItemUI extends View {
		public var btnsel:Button;
		public var selCheck:Radio;
		public var addresstxt:Label;
		public var btnSetDefault:Text;
		public var defaultMark:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1646,"height":46},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"width":1362,"var":"btnsel","skin":"order1/chooseadd.png","sizeGrid":"3,3,3,3","height":46},"compId":6},{"type":"Radio","props":{"y":14,"x":22,"var":"selCheck","skin":"uiCommonUpdate/checksel.png","mouseEnabled":false},"compId":7},{"type":"Label","props":{"y":11,"x":60,"width":1288,"var":"addresstxt","text":"浙江省 金华市 义乌市 抽成街道","overflow":"scroll","mouseEnabled":false,"height":24,"fontSize":24,"font":"SimHei","color":"#262B2E"},"compId":8},{"type":"Text","props":{"y":10,"x":1445.5,"width":92,"var":"btnSetDefault","text":"设为默认","presetID":1,"height":26,"fontSize":24,"font":"SimHei","color":"#003dc6","isPresetRoot":true,"runtime":"laya.display.Text"},"compId":11,"child":[{"type":"Script","props":{"presetID":2,"runtime":"script.prefabScript.LinkTextControl"},"compId":12}]},{"type":"Button","props":{"y":0,"width":249,"var":"defaultMark","skin":"uiCommonUpdate/greenBtn.png","selected":true,"right":30,"labelSize":24,"labelFont":"SimHei","labelColors":"#FFFFFF,#FFFFFF,#FFFFFF,","label":"已设为默认地址","height":46,"sizeGrid":"2,22,3,22"},"compId":13}],"loadList":["order1/chooseadd.png","uiCommonUpdate/checksel.png","prefabs/LinksText.prefab","uiCommonUpdate/greenBtn.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}