/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.OderTopFlowController;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.order.PackageVipController;

	public class PackageOrderPanelUI extends View {
		public var mainpanel:Panel;
		public var packagepanel:Panel;
		public var curPackgaeNum:Label;
		public var addpackbtn:Button;
		public var productbox:VBox;
		public var packagelist:List;
		public var step1:Box;
		public var step2:Box;
		public var step3:Box;
		public var step4:Box;
		public var productNum:Label;
		public var textPayPrice:Label;
		public var textDiscount:Label;
		public var textTotalPrice:Label;
		public var cancelbtn:Button;
		public var timepreferRdo:RadioGroup;
		public var okbtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/PackageOrderPanel");

		}

	}
}