/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;

	public class PackageNumItemUI extends Scene {
		public var numInput:TextInput;
		public var addBtn:Button;
		public var subBtn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"Scene","props":{"width":135,"height":140},"compId":2,"child":[{"type":"Box","props":{"y":0,"x":36,"width":62,"height":140},"compId":3,"child":[{"type":"TextInput","props":{"y":56,"x":2,"width":57,"var":"numInput","type":"number","text":"100","skin":"commers/inputbg.png","sizeGrid":"3,3,3,3","height":22,"fontSize":18,"font":"SimHei","align":"center"},"compId":4},{"type":"Button","props":{"y":25,"x":17,"width":27,"var":"addBtn","skin":"uiCommonUpdate/blackbtn.png","labelSize":25,"labelFont":"SimHei","labelColors":"#FFFFFF,#0,#FFFFFF","label":"+","height":27,"sizeGrid":"7,5,8,4"},"compId":6},{"type":"Button","props":{"y":84,"x":17,"width":27,"var":"subBtn","skin":"uiCommonUpdate/blackbtn.png","labelSize":25,"labelFont":"SimHei","labelColors":"#FFFFFF,#0,#FFFFFF","label":"-","height":27,"sizeGrid":"7,5,8,4"},"compId":7}]},{"type":"Image","props":{"y":0,"x":0,"skin":"commers/cutline.png","right":0,"left":0,"height":1,"bottom":1},"compId":8}],"loadList":["commers/inputbg.png","uiCommonUpdate/blackbtn.png","commers/cutline.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}