/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;
	import script.order.SelectPackAddressController;

	public class SelectPackAddresstPanelUI extends Scene {
		public var groupTab:Button;
		public var addressTab:Button;
		public var addressbox:Box;
		public var btnSelArea:Button;
		public var areatxt:Label;
		public var btnSelCity:Button;
		public var citytxt:Label;
		public var btnSelProv:Button;
		public var province:Label;
		public var addressList:List;
		public var searchInput:TextInput;
		public var searchbtn:Button;
		public var selectall:CheckBox;
		public var pageNum:Label;
		public var prePage:Button;
		public var nextPage:Button;
		public var provbox:Image;
		public var provList:List;
		public var citybox:Image;
		public var cityList:List;
		public var areabox:Image;
		public var areaList:List;
		public var groupBox:Box;
		public var groupList:List;
		public var searchGroupInput:TextInput;
		public var searchGrpBtn:Button;
		public var grPageNum:Label;
		public var gpPrevPage:Button;
		public var gpNextPage:Button;
		public var closebtn:Button;
		public var okbtn:Button;
		public var selectNum:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("order/SelectPackAddresstPanel");

		}

	}
}