/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.order {
	import laya.ui.*;
	import laya.display.*;

	public class TabChooseBtnUI extends View {
		public var selbtn:Button;
		public var selfIcon:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"width":287,"var":"selbtn","stateNum":3,"skin":"uiCommonUpdate/matBtn.png","labelSize":24,"labelFont":"SimHei","labelColors":"#262B2E,#003dc6,#003dc6","label":"户内PP背胶（户内写真）","height":42,"sizeGrid":"7,23,12,28"},"compId":3},{"type":"Image","props":{"y":0,"x":255,"width":20,"var":"selfIcon","skin":"commers/client.png","mouseEnabled":false,"height":20},"compId":4}],"loadList":["uiCommonUpdate/matBtn.png","commers/client.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}