/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.uploadpic {
	import laya.ui.*;
	import laya.display.*;

	public class UpLoadItemUI extends View {
		public var filename:Label;
		public var prog:Label;
		public var isuploading:Label;
		public var btncancel:Button;
		public var finishimg:Sprite;
		public var reUploadBtn:Button;
		public var unnormal:Label;
		public var prgbar:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1724,"height":100},"compId":2,"child":[{"type":"Image","props":{"top":0,"skin":"commers/graydisable.jpg","sizeGrid":"3,3,3,3","right":0,"left":0,"bottom":0},"compId":18},{"type":"Label","props":{"y":39,"x":167,"width":418,"var":"filename","text":"文件名","overflow":"hidden","height":21,"fontSize":24,"font":"SimHei","color":"#262B2E","align":"left"},"compId":3},{"type":"Label","props":{"y":38,"x":776,"var":"prog","text":"10%","height":24,"fontSize":24,"font":"SimHei","color":"#0","align":"left"},"compId":6},{"type":"Label","props":{"y":39,"x":1028,"width":78,"visible":true,"var":"isuploading","text":"等待中...","fontSize":24,"font":"SimHei","color":"#B1B1B1","align":"right"},"compId":7},{"type":"Button","props":{"y":38,"x":1579,"var":"btncancel","stateNum":1,"skin":"iconsNew/rubish.png"},"compId":9,"child":[{"type":"Label","props":{"y":0,"x":29,"text":"取消上传","fontSize":24,"font":"SimHei","color":"#B1B1B1"},"compId":21}]},{"type":"Sprite","props":{"y":41,"x":1329,"var":"finishimg","texture":"upload1/finishicon.png"},"compId":15},{"type":"Button","props":{"y":50,"x":1455,"var":"reUploadBtn","stateNum":1,"skin":"uiCommonUpdate/xiala.png","rotation":-90,"anchorY":0.5,"anchorX":0.5},"compId":16},{"type":"Label","props":{"y":39,"x":506,"width":196,"var":"unnormal","text":"文件大小异常，取消上传","overflow":"hidden","height":21,"fontSize":24,"font":"SimHei","color":"#f93d0e","align":"left"},"compId":17},{"type":"Image","props":{"y":10,"x":10,"width":80,"skin":"bigImg/face.png","height":80},"compId":19},{"type":"Image","props":{"width":965,"var":"prgbar","skin":"uiCommonUpdate/orderTypeBtn.png","sizeGrid":"3,3,3,3","left":110,"height":13,"bottom":0},"compId":20}],"loadList":["commers/graydisable.jpg","iconsNew/rubish.png","upload1/finishicon.png","uiCommonUpdate/xiala.png","bigImg/face.png","uiCommonUpdate/orderTypeBtn.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}