/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import script.uiTool.BtnMouseCusor;
	import script.FirstPageController;

	public class FirstPagePanelUI extends Scene {
		public var mainPanel:Panel;
		public var leftMenuPanel:Panel;
		public var gotoFirst:Image;
		public var headimg:Image;
		public var accountlbl:Label;
		public var exitBtn:Label;
		public var workBtn:Button;
		public var picBtn:Button;
		public var orderbtn:Button;
		public var companyBtn:Button;
		public var moneyBtn:Button;
		public var settingBtn:Button;
		public var coverbg:Image;
		public var contentPanel:Panel;
		public var shrinkBtn:Image;
		public var arrow:Image;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("FirstPagePanel");

		}

	}
}