/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui {
	import laya.ui.*;
	import laya.display.*;
	import utils.PopUpWindowControl;

	public class PopUpPhoneDialogUI extends View {
		public var mainpanel:Panel;
		public var mainview:Image;
		public var msgtxt:Label;
		public var tips:Label;
		public var btnSp:Sprite;
		public var okbtn:Button;
		public var cancelbtn:Button;
		public var closebtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("PopUpPhoneDialog");

		}

	}
}