/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.login {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.CmykInputControl;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;
	import script.login.RegisterCntrol;

	public class RegisterPhonePanelUI extends View {
		public var mainpanel:Panel;
		public var bgimg:Image;
		public var gotoFirst:Image;
		public var firstStep:Image;
		public var firstLine:Image;
		public var sencondStep:Image;
		public var step1Panel:Box;
		public var input_phone:TextInput;
		public var delBtn:Button;
		public var nameInput:TextInput;
		public var delBtn:Button;
		public var input_pwd:TextInput;
		public var delBtn:Button;
		public var input_conpwd:TextInput;
		public var conpwdError:Label;
		public var delBtn:Button;
		public var code0:Label;
		public var code1:Label;
		public var code2:Label;
		public var code3:Label;
		public var imgCodeInput:Image;
		public var inputCode:TextInput;
		public var delBtn:Button;
		public var btnGetCode:Button;
		public var input_phonecode:TextInput;
		public var delBtn:Button;
		public var txtRefresh:Text;
		public var gotoNext:Button;
		public var step2Panel:Box;
		public var input_companyname:TextInput;
		public var delBtn:Button;
		public var contactName:TextInput;
		public var delBtn:Button;
		public var contactPhone:TextInput;
		public var delBtn:Button;
		public var detail_addr:TextInput;
		public var delBtn:Button;
		public var btnSelProv:Button;
		public var province:Label;
		public var btnSelCity:Button;
		public var citytxt:Label;
		public var btnSelArea:Button;
		public var areatxt:Label;
		public var btnSelTown:Button;
		public var towntxt:Label;
		public var townbox:Image;
		public var townList:List;
		public var areabox:Image;
		public var areaList:List;
		public var citybox:Image;
		public var cityList:List;
		public var provbox:Image;
		public var provList:List;
		public var applyBtn:Button;
		public var applyEnter:Button;
		public var applyJoinPanel:Image;
		public var createAccountInput:TextInput;
		public var delBtn:Button;
		public var commentInput:TextInput;
		public var delBtn:Button;
		public var confirmJoin:Button;
		public var closeJoin:Button;
		public var contractpanel:Panel;
		public var txtpanel:Panel;
		public var sevicepro:Text;
		public var agreebox:CheckBox;
		public var okbtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("login/RegisterPhonePanel");

		}

	}
}