/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.AddrGroupMgrController;

	public class AddrGroupDetailPanelUI extends Scene {
		public var dragImg:Image;
		public var grpName:Label;
		public var addressList:List;
		public var searchInput:TextInput;
		public var searchbtn:Button;
		public var selectall:CheckBox;
		public var delBatchBtn:Button;
		public var pageNum:Label;
		public var prePage:Button;
		public var nextPage:Button;
		public var addAddrbtn:Button;
		public var closebtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/AddrGroupDetailPanel");

		}

	}
}