/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class AddressGroupItemUI extends View {
		public var btn:Button;
		public var deletbtn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Button","props":{"width":150,"var":"btn","skin":"commers/btn2.png","sizeGrid":"3,3,3,3","labelSize":14,"labelFont":"Arial","labelColors":"#232b26,#006600,#232b26","labelBold":true,"height":60},"compId":4,"child":[{"type":"Button","props":{"y":2,"x":129,"var":"deletbtn","skin":"commers/btnclose.png"},"compId":5}]}],"loadList":["commers/btn2.png","commers/btnclose.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}