/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.AddressGroupController;

	public class AddressGroupPanelUI extends View {
		public var addAddress:Button;
		public var addGroup:Button;
		public var addressTab:Button;
		public var groupTab:Button;
		public var addressbox:Box;
		public var addressList:List;
		public var searchInput:TextInput;
		public var searchAddressBtn:Button;
		public var selectall:CheckBox;
		public var delBatchBtn:Button;
		public var btnSelProv:Button;
		public var province:Label;
		public var btnSelCity:Button;
		public var citytxt:Label;
		public var btnSelArea:Button;
		public var areatxt:Label;
		public var provbox:Image;
		public var provList:List;
		public var citybox:Image;
		public var cityList:List;
		public var areabox:Image;
		public var areaList:List;
		public var pageNum:Label;
		public var prePage:Button;
		public var nextPage:Button;
		public var groupBox:Box;
		public var groupList:List;
		public var searchGroupInput:TextInput;
		public var searchGrpBtn:Button;
		public var createGroupBox:Box;
		public var newGroupName:TextInput;
		public var confirmCreateGroup:Button;
		public var closeNewGroup:Button;
		public var grPageNum:Label;
		public var gpPrevPage:Button;
		public var gpNextPage:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/AddressGroupPanel");

		}

	}
}