/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.AddressListController;

	public class AddressListPanelUI extends Scene {
		public var dragImg:Image;
		public var btnSelArea:Button;
		public var areatxt:Label;
		public var btnSelCity:Button;
		public var citytxt:Label;
		public var btnSelProv:Button;
		public var province:Label;
		public var addressList:List;
		public var searchInput:TextInput;
		public var searchbtn:Button;
		public var selectall:CheckBox;
		public var pageNum:Label;
		public var prePage:Button;
		public var nextPage:Button;
		public var hidebtn:CheckBox;
		public var provbox:Image;
		public var provList:List;
		public var citybox:Image;
		public var cityList:List;
		public var areabox:Image;
		public var areaList:List;
		public var closebtn:Button;
		public var okbtn:Button;
		public var selectNum:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/AddressListPanel");

		}

	}
}