/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.ChargeControl;

	public class ChargePanelUI extends View {
		public var accout:Label;
		public var moneytxt:Label;
		public var factoryFreezMoney:Label;
		public var factoryMoney:Label;
		public var finishcharge:Button;
		public var chargerecord:Button;
		public var copyname:Button;
		public var companyname:Label;
		public var bank:Label;
		public var copybank:Button;
		public var account:Label;
		public var copyaccount:Button;
		public var chargeinput:TextInput;
		public var confirmcharge:Button;
		public var inputmoneypanel:Box;
		public var sendcharge:Button;
		public var closeinput:Button;
		public var confirmmoney:TextInput;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/ChargePanel");

		}

	}
}