/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class DeliveryPackageItemUI extends View {
		public var btn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":0,"height":0},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"width":359,"var":"btn","skin":"uiCommonUpdate/greenBtn.png","labelSize":24,"labelColors":"#FFFFFF,#FFFFFF,#FFFFFF,","labelBold":true,"label":"包裹1（点击查询物流详情）","height":88,"sizeGrid":"2,22,3,22"},"compId":4}],"loadList":["uiCommonUpdate/greenBtn.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}