/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.DeliveryQueryController;

	public class DeliveryQueryPanelUI extends View {
		public var mainpanel:Panel;
		public var closebtn:Button;
		public var packageList:List;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/DeliveryQueryPanel");

		}

	}
}