/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class InvoiceDailyItemUI extends View {
		public var manufacture:Label;
		public var timetxt:Label;
		public var money:Label;
		public var state:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"x":0,"width":630,"skin":"commers/graydisable.jpg","sizeGrid":"2,2,2,2","height":35,"alpha":0.5},"compId":8},{"type":"Label","props":{"y":0,"x":0,"width":181,"var":"manufacture","valign":"middle","text":"浙江禾物喷印","height":38,"fontSize":18,"font":"SimHei","align":"center"},"compId":3},{"type":"Label","props":{"y":0,"x":177,"width":169,"var":"timetxt","valign":"middle","text":"2021-01-01","height":38,"fontSize":18,"font":"SimHei","align":"center"},"compId":4},{"type":"Label","props":{"y":0,"x":379,"width":121,"var":"money","valign":"middle","text":"￥15689","height":38,"fontSize":18,"font":"SimHei","align":"center"},"compId":5},{"type":"Label","props":{"y":0,"x":518,"width":121,"var":"state","valign":"middle","text":"待开票","height":38,"fontSize":18,"font":"SimHei","color":"#f31310","align":"center"},"compId":7}],"loadList":["commers/graydisable.jpg"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}