/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.InvoiceHistoryController;

	public class InvoiceHistoryPanelUI extends View {
		public var dragimg:Image;
		public var invoicelist:List;
		public var closebtn:Button;
		public var ordertime:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/InvoiceHistoryPanel");

		}

	}
}