/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.InvoiceManager;

	public class InvoiceManagerPanelUI extends View {
		public var ordertime:Label;
		public var companyInfoBtn:Button;
		public var adressBtn:Button;
		public var detailBtn:Button;
		public var invoiceHistory:Button;
		public var invoicelist:List;
		public var invoiceNum:Label;
		public var totalMoney:Label;
		public var queryBtn:Button;
		public var confirmInvoiceBtn:Button;
		public var detailbox:Box;
		public var closedetail:Button;
		public var detaillist:List;
		public var enterprizeInfoPanel:Box;
		public var companyName:TextInput;
		public var taxNumber:TextInput;
		public var bankName:TextInput;
		public var updateOK:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/InvoiceManagerPanel");

		}

	}
}