/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.OrderDetailControl;

	public class OrderDetailPanelUI extends View {
		public var mainpanel:Panel;
		public var orderSn:Label;
		public var orderoanel:Panel;
		public var orderbox:List;
		public var closebtn:Button;
		public var orderState:Label;
		public var moneyPaidlbl:Label;
		public var prodNum:Label;
		public var orderTime:Label;
		public var address:Label;
		public var comondeltype:Label;
		public var urgentdelType:Label;
		public var outputtxt:Label;
		public var deliveryState:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/OrderDetailPanel");

		}

	}
}