/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class OrganizeItemUI extends View {
		public var hotbtm:Button;
		public var deltbn:Button;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Button","props":{"y":0,"x":0,"width":112,"var":"hotbtm","staticCache":false,"skin":"uiCommonUpdate/green2.png","sizeGrid":"3,3,3,3","selected":false,"labelSize":16,"labelFont":"SimHei","labelColors":"#003dc6,#003dc6,#FFFFFF","label":"浦东三点瑞普","height":40},"compId":3},{"type":"Button","props":{"y":1,"x":92,"width":12,"var":"deltbn","stateNum":1,"skin":"uiCommonUpdate/closeGray.png","labelSize":16,"labelFont":"SimHei","labelColors":"#FFFFFF,#FFFFFF,#FFFFFF","height":12},"compId":4}],"loadList":["uiCommonUpdate/green2.png","uiCommonUpdate/closeGray.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}