/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class PublicChargeRecordItemUI extends View {
		public var transfermoney:Label;
		public var chargemoney:Label;
		public var confirmtime:Label;
		public var chargetime:Label;
		public var state:Label;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{},"compId":2,"child":[{"type":"Image","props":{"y":0,"x":0,"width":1000,"skin":"commers/inputbg.png","sizeGrid":"5,5,5,5","height":60},"compId":3,"child":[{"type":"Sprite","props":{"y":0,"x":0},"compId":21,"child":[{"type":"Rect","props":{"width":1000,"lineWidth":1,"height":60,"fillColor":"#eff4ef"},"compId":22}]}]},{"type":"Label","props":{"y":5,"x":16,"wordWrap":true,"width":118,"var":"transfermoney","valign":"middle","text":"15000","overflow":"hidden","height":50,"fontSize":20,"font":"Arial","color":"#262B2E","align":"center"},"compId":7},{"type":"Label","props":{"y":5,"x":177,"wordWrap":true,"width":153,"var":"chargemoney","valign":"middle","text":"2","height":50,"fontSize":20,"font":"Arial","color":"#262B2E","align":"center"},"compId":27},{"type":"Label","props":{"y":5,"x":350,"wordWrap":true,"width":202,"var":"confirmtime","valign":"middle","text":"2021-09-12 12:21:21","overflow":"hidden","height":50,"fontSize":20,"font":"Arial","color":"#262B2E","align":"center"},"compId":59},{"type":"Label","props":{"y":5,"x":600,"wordWrap":true,"width":200,"var":"chargetime","valign":"middle","text":"2021-12-12 15:00:00","overflow":"hidden","height":50,"fontSize":20,"font":"Arial","color":"#262B2E","align":"center"},"compId":60},{"type":"Label","props":{"y":5,"x":850,"wordWrap":true,"width":81,"var":"state","valign":"middle","text":"已确认","height":50,"fontSize":20,"font":"SimHei","color":"#508d38","align":"center"},"compId":63}],"loadList":["commers/inputbg.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}