/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.PublicChargeRecordController;

	public class PublicChargeRecordPanelUI extends View {
		public var recordlist:List;
		public var closebtn:Button;
		public var pagetxt:Label;
		public var prevbtn:Button;
		public var nextbtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/PublicChargeRecordPanel");

		}

	}
}